class FlightData:
    """creates a FlightData object containing
    DATE,FLIGHT_ID,DEP_ARR,FLIGHTNUM_MAIN,TIME,STATUS,ACTUAL_TIME,DESTINATION_IATA,AIRLINE_CODE,DESTINATION,AIRLINE,
    CODESHARE,WEEKDAY (generated by function)"""
    def __init__(self, flight_date="1981_01_24", flight_id="19810124RYK2401", dep_arr="DEPARR", flight_num="RYK2401",
                 departure="24:01 Uhr", status="departed", actual_time="06:00 Uhr", dest_iata="YKR", airline_code="N7",
                 destination="Rome", airline="SerenityAir", codeshare="NCC1701", weekday="sAt"):
        self.flight_date = flight_date
        self.flight_id = flight_id
        self.dep_arr = dep_arr
        self.flight_num = flight_num
        self.departure = departure
        self.status = status
        self.actual_time = actual_time
        self.dest_iata = dest_iata
        self.airline_code = airline_code
        self.destination = destination
        self.airline = airline
        self.codeshare = codeshare
        self.weekday = weekday

    def __repr__(self):
        return f"FlightData object with flight id of {self.flight_id}"

    def __dir__(self):
        return ["flight_date, flight_id, dep_arr, flight_num, departure, status, actual_time, "
                "dest_iata, airline_code, destination, airline, codeshare, weekday"]
